// Datos generados a partir de "INFO GENERAL INTERCONSULTORES 2026.numbers".
// Directorio de profesionales o entidades interconsultores — Junta Regional de Santander.
// Texto normalizado (Title Case) y con correcciones de erratas y columnas cruzadas del origen.

export interface Interconsultor {
  nombre: string;
  especialidad: string;
  direccion: string;
  telefono: string;
  correo: string;
}

export const interconsultores: Interconsultor[] = [
  {
    nombre: "Javier Fajardo -Cuidados Respiratorios Integrales SAS",
    especialidad: "Neumologia",
    direccion: "Av Gonzalez Valencia Clz # 55A-54",
    telefono: "3153280686",
    correo: "cri.bucaramanga@gmail.com",
  },
  {
    nombre: "Silvia Liliana Ruiz Cala",
    especialidad: "Psiquiatra",
    direccion: "Calle 50 # 23-100",
    telefono: "6432812",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Lucia Quintero Isaza",
    especialidad: "Psiquiatra",
    direccion: "Calle 50 # 23-100",
    telefono: "6432812",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Heidi Celina Oviedo Acevedo",
    especialidad: "Psiquiatra",
    direccion: "Calle 50 # 23-100",
    telefono: "6432812",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Henry Alberto Porras Angarita",
    especialidad: "Psiquiatra",
    direccion: "Calle 50 # 23-100",
    telefono: "6432812",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Donaldo Ortiz Latorre",
    especialidad: "Dermatologia",
    direccion: "Carrera 29 # 48-45",
    telefono: "6571828",
    correo: "donaldoortiz@gmail.com",
  },
  {
    nombre: "Yamile Jaime Claro",
    especialidad: "Fonoaudiologia",
    direccion: "Av Gonzalez Valencia #55B-10 Clinica Metropolitana",
    telefono: "6570420",
    correo: "",
  },
  {
    nombre: "Leonardo Alvarez Osorio",
    especialidad: "Oftalmologia",
    direccion: "Calle 89 # 17C-10",
    telefono: "3154165632",
    correo: "leonardoalvarez@hotmail.com",
  },
  {
    nombre: "Luis Alejandro Gomez Buitrago",
    especialidad: "Optometria",
    direccion: "Calle 43 # 26-32 Giron",
    telefono: "6460626",
    correo: "alejoptom@hotmail.com",
  },
  {
    nombre: "Miguel Reyes Guerrero",
    especialidad: "Cirugia plastica maxilofacial y mano",
    direccion: "Calle 49 #27 A -65 Consultorio 506",
    telefono: "6193286",
    correo: "miguelreyescirplastico@hotmail.com",
  },
  {
    nombre: "Genny Liliana Melendez Florez",
    especialidad: "Cirugia plastica reconstructiva",
    direccion: "Calle 49 #27 A -65 Consultorio 506",
    telefono: "6193286",
    correo: "dramelendezplastica@yahoo.com",
  },
  {
    nombre: "German Eduardo Rueda Jaimes",
    especialidad: "Psiquiatra",
    direccion: "Calle 49 # 28-10 Consultorio 310",
    telefono: "6572043",
    correo: "gredu@unab.edu.co",
  },
  {
    nombre: "Olga Patricia Rugeles Hernandez",
    especialidad: "Fisioterapeuta",
    direccion: "Carrera 12 #1A-12 la Macarena",
    telefono: "3108517514",
    correo: "p_rugeles@hotmail.com",
  },
  {
    nombre: "Olga Rosa Castillo Mier",
    especialidad: "Otorrinolaringologia",
    direccion: "CM Carlos Ardila Lulle T A Mod 36 Cons 716",
    telefono: "6076384160 -3204495543",
    correo: "otocenter.admin@gmail.com -administracion@otocenter.com.co",
  },
  {
    nombre: "Carlos Alberto Alvarez Cortes",
    especialidad: "Fisiatria",
    direccion: "Carrera 36 # 46- 89 Cons 405",
    telefono: "6850245",
    correo: "cabetoalv@hotmail.com",
  },
  {
    nombre: "Luis Homero Alvarez Acevedo",
    especialidad: "Fisiatria",
    direccion: "CM Carlos Ardila Lulle Mod 9 Piso 3",
    telefono: "6384160",
    correo: "",
  },
  {
    nombre: "Angela Marcela Capacho",
    especialidad: "Fonoaudiologia",
    direccion: "Mirador del Valle T 7 Apto 204 Trnv 154 157A-40",
    telefono: "6905371",
    correo: "angelmarcav5@hotmail.com",
  },
  {
    nombre: "Eslabonar",
    especialidad: "Salud ocupacional",
    direccion: "Carrera 21 # 53-24 Brr Concordia",
    telefono: "6174070",
    correo: "comercial.eslabonar@gmail.com - gestionhumana.eslabonar@gmail.com",
  },
  {
    nombre: "Yolanda Cruz Serrano",
    especialidad: "Fisioterapeuta",
    direccion: "Carrera 28 #41-27",
    telefono: "3163775380",
    correo: "yolanda65cruz@hotmail.com",
  },
  {
    nombre: "German Eduardo Cardenas Arenas",
    especialidad: "Ortopedia y traumatologia",
    direccion: "Carrera 33 # 52-123",
    telefono: "6439403-6824410",
    correo: "adoctorgermancardenas@gmail.com",
  },
  {
    nombre: "Luz Stella Montoya de Bayona",
    especialidad: "Dermatologia",
    direccion: "CM Carlos Ardila Lulle",
    telefono: "6394041",
    correo: "luzmontoya24@hotmail.com",
  },
  {
    nombre: "Nestor Fabian Gomez Pinto",
    especialidad: "Fisiatria-ginecobstetra",
    direccion: "Circunvalar 35 # 92-170",
    telefono: "3014246374",
    correo: "fabigomezp@gmail.com",
  },
  {
    nombre: "Sisocol Cabarcas SAS",
    especialidad: "Salud ocupacional",
    direccion: "Calle 53#36-08 Piso 2",
    telefono: "6577788",
    correo: "sisocol.cc@gmail.com",
  },
  {
    nombre: "Alid Cañizares Cepeda",
    especialidad: "Psicologia",
    direccion: "Calle 53#36-08 Piso 2",
    telefono: "6577788",
    correo: "sisocol.cc@gmail.com",
  },
  {
    nombre: "Rafael Eduardo Benavides Gelvez",
    especialidad: "Psiquiatria",
    direccion: "Clinica Isnor",
    telefono: "6432364",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Lina Marcela Luna Ordoñez",
    especialidad: "Psicologia",
    direccion: "Calle 105#24-75 Ofc 1 Provenza",
    telefono: "3164739223",
    correo: "gerencia@thi.com.co",
  },
  {
    nombre: "Liliana Isleny Diaz Soto",
    especialidad: "Psiquiatria",
    direccion: "Clinica Isnor",
    telefono: "6432364",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Clinica Isnor",
    especialidad: "Psiquiatria",
    direccion: "Calle 50 # 23-100",
    telefono: "6432364",
    correo: "gerencia@clinicaisnor.com",
  },
  {
    nombre: "Fundacion Cardiovascular",
    especialidad: "Especialistas",
    direccion: "Calle 155A # 23-58 Urbanizacion El Bosque",
    telefono: "6399292",
    correo: "www.fcv.org",
  },
  {
    nombre: "Hospital Psiquiatrico San Camilo",
    especialidad: "Especialistas",
    direccion: "",
    telefono: "",
    correo: "subcientifica@hospitalsancamilo.gov.co",
  },
  {
    nombre: "Carlos Abel Quintero Diaz",
    especialidad: "Neurologo",
    direccion: "H. Psiquiatrico San Camilo",
    telefono: "",
    correo: "",
  },
  {
    nombre: "Blanca Margarita Barrera Gonzalez",
    especialidad: "Psiquiatra",
    direccion: "H. Psiquiatrico San Camilo",
    telefono: "",
    correo: "",
  },
  {
    nombre: "Centro Oftalmologico Virgilio Galvis",
    especialidad: "Oftalmologia",
    direccion: "Centro Medico Carlos Ardila Lulle",
    telefono: "6392929",
    correo: "servicioalcliente@virgiliogalvis.com.co",
  },
  {
    nombre: "Carlos Hernando Rico",
    especialidad: "Fisiatra",
    direccion: "Calle 42 #35-58 Cons. 408. Centro Clínico Quirúrgico.",
    telefono: "6076350248- 3152843506",
    correo: "cahribe2000@hotmail.com",
  },
  {
    nombre: "Clinica del Dolor Aliviar",
    especialidad: "Clinica del dolor",
    direccion: "Centro Medico Carlos Ardila Lulle",
    telefono: "6046854567",
    correo: "talentohumano@clinicadeldoloraliviar.com",
  },
  {
    nombre: "Medicity - Dr. Diego Luis Saaibi",
    especialidad: "Medicina interna",
    direccion: "",
    telefono: "",
    correo: "gerencia@medicity.com.co",
  },
  {
    nombre: "Dr. Carlos Enrique Maiguel Carrizosa",
    especialidad: "Neurocirujano",
    direccion: "Carrera24 # 154-106 Cons. 505 Mod. 18 Torre A - Bucaramanga",
    telefono: "6384160 Ext 1594",
    correo: "consultorio505.modulo18@gmail.com",
  },
  {
    nombre: "Rocio Ibette Mantilla Gomez",
    especialidad: "Fisioterapeuta",
    direccion: "",
    telefono: "3224021137",
    correo: "",
  },
  {
    nombre: "SIMAG",
    especialidad: "Ecografias",
    direccion: "",
    telefono: "6439111",
    correo: "simagparamedicos@hotmail.com",
  },
  {
    nombre: "Instituto Neumologico del Oriente",
    especialidad: "Neumologia",
    direccion: "Cll. 53 # 31 – 30",
    telefono: "607 6972473 - 3103014562",
    correo: "cotizaciones@ino.com.co; convenios@ino.com.co; facturacion.cartera@ino.com.co",
  },
  {
    nombre: "Mario Bueno Duran",
    especialidad: "Neurocirujano",
    direccion: "",
    telefono: "3155530733",
    correo: "consultoriomariobueno@gmail.com",
  },
  {
    nombre: "Gabriel Vargas",
    especialidad: "Neurocirujano",
    direccion: "",
    telefono: "3168262081",
    correo: "neurovargas308@hotmail.com - gabrielvargasneurocirujia@gmail.com",
  },
  {
    nombre: "CATME",
    especialidad: "Imágenes diagnosticas",
    direccion: "",
    telefono: "6076059440",
    correo: "citascatme@hotmail.com; coordinacion@catme.com.co; direccionadministrativa@catme.com.co",
  },
  {
    nombre: "William Omar Contreras",
    especialidad: "Neurocirujano",
    direccion: "",
    telefono: "3212597617",
    correo: "nemos.recepcion@hotmail.com",
  },
  {
    nombre: "Audiofon",
    especialidad: "",
    direccion: "",
    telefono: "6076185555",
    correo: "comercial.audiofon@gmail.com",
  },
  {
    nombre: "Ivan Dario Freire",
    especialidad: "Neurocirujano",
    direccion: "",
    telefono: "3123505325",
    correo: "ifreire66@gmail.com - freireneurocirugis@gmail.com",
  },
  {
    nombre: "Carlos Andres Calderon",
    especialidad: "Reumatologia",
    direccion: "",
    telefono: "3023868410",
    correo: "reumatologia@carloscalderon@gmail.com",
  },
  {
    nombre: "IGHO SAS",
    especialidad: "Gastroenterologia",
    direccion: "",
    telefono: "6076470047 ext 130",
    correo: "comercialymercadeo@ighosas.com",
  },
  {
    nombre: "Neftali Cosio",
    especialidad: "Neurocirugia",
    direccion: "CM Carlos Ardila, Torre A, Piso 7, Modulo 34",
    telefono: "6384160 EXT 1717 - 3166916243 - 3104625811",
    correo: "modulo34,7@hotmail.com",
  },
  {
    nombre: "Javier Serrano",
    especialidad: "Cirujano general",
    direccion: "",
    telefono: "321 7648493",
    correo: "jaadsejo@hotmail.com",
  },
];
